name: titanic_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - mlflow
      - dagshub
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - joblib